nodeLinker: pnp

npmScopes:
  saber-hq:
    npmAlwaysAuth: true
    npmAuthToken: "${SABER_GH_PACKAGE_REGISTRY_PAT}"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
