slug = "sbr"
name = "Saber"
address = "9tnpMysuibKx6SatcH3CWR9ZsSRMBNeBf1mhfL6gAXR4"
description = "AMM for mean-reverting trading pairs on Solana"

[proposals]
requiredDiscussionLink = "https://gov.saber.so/c/saber-community-proposals/6"

[minter]
mintWrapper = "EVVDA3ZiAjTizemLGXNUN3gb6cffQFEYkFjFZokPmUPz"
redeemer = "CL9wkGFT3SZRRNa9dgaovuRV7jrVVigBUZ6DjcgySsCU"

[links]
website = "https://saber.so"
app = "https://app.saber.so"
forum = "https://gov.saber.so"
discord = "https://chat.saber.so"
github = "https://github.com/saber-hq"
medium = "https://blog.saber.so"
twitter = "https://twitter.com/saber_hq"

[govToken]
address = "Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1"

[gauge]
gaugemeister = "28ZDtf6d2wsYhBvabTxUHTRT6MDxqjmqR7RMCp348tyU"
hidden = true
