name: CI

on:
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          always-auth: true
          registry-url: "https://npm.pkg.github.com"
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('./.yarn/**/*.js') }}
          path: ./.yarn
      - run: yarn install
      - run: yarn build
